### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [kennysunstone/teacozy#5]
Great job on this project - I really liked how you styled the nav, as well as how you chose to set up your copyright. In terms of improvement, I recommend creating a general flex class, giving mission and locations a margin of 0 auto, and overriding the default body margin of 8px.

If you’re in the mood for a challenge, I would look into implementing a mobile version of this page! Here's a link to get you started: https://www.w3schools.com/css/css_rwd_mediaqueries.asp. Keep up the hard work! ^_^

**Comment by kennysunstone** [comment]
Thanks for the review and ideas very helpful. Will take a look at the mobile stuff over the weekend.
